name: ratel-wai
version: 1.0.6

category: Exceptions
description: ratel-wai notifies Honeybadger about exceptions via a WAI middleware.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/ratel-wai
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Notify Honeybadger about exceptions via a WAI middleware.

dependencies:
  base: '>= 4.9.0 && < 4.13'
  bytestring: '>= 0.10.8 && < 0.11'
  case-insensitive: '>= 1.2.0 && < 1.3'
  containers: '>= 0.5.7 && < 0.7'
  http-client: '>= 0.4.31 && < 0.7'
  ratel: '>= 0.3.1 && < 0.4 || >= 1.0.2 && < 1.1'
  wai: '>= 3.2.1 && < 3.3'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library
